Importing pandas library

In [1]:
import pandas as pd

basic structure

In [4]:
pd.DataFrame({"Yes":[1,2,3],"No":[4,5,6]})

   Yes  No
0    1   4
1    2   5
2    3   6

In [10]:
pd.DataFrame({"Yes": [1,2,3],"No":[4,5,6]}, index=["first","second","third"])

        Yes  No
first     1   4
second    2   5
third     3   6

In [15]:
datas = [
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
]
pd.DataFrame(datas, columns=["A","B","C"], index=[1, 2, 3, 4])

    A   B   C
1   1   2   3
2   4   5   6
3   7   8   9
4  10  11  12

In [37]:
df = pd.DataFrame(datas, columns=["A","B","C"], index=[1, 2, 3, 4])
df.shape

(4, 3)

In [40]:
df.info

<bound method DataFrame.info of     A   B   C
1   1   2   3
2   4   5   6
3   7   8   9
4  10  11  12>

In [35]:
df.head(3)

   A  B  C
1  1  2  3
2  4  5  6
3  7  8  9

In [36]:
df.tail(3)

    A   B   C
2   4   5   6
3   7   8   9
4  10  11  12